// Code generated by Kitex v0.3.4. DO NOT EDIT.

package appservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	"mgr-demo2/kitex_gen/thrift/kitex/api"
)

func serviceInfo() *kitex.ServiceInfo {
	return appServiceServiceInfo
}

var appServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "AppService"
	handlerType := (*api.AppService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Action": kitex.NewMethodInfo(actionHandler, newAppServiceActionArgs, newAppServiceActionResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.3.4",
		Extra:           extra,
	}
	return svcInfo
}

func actionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.AppServiceActionArgs)
	realResult := result.(*api.AppServiceActionResult)
	success, err := handler.(api.AppService).Action(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAppServiceActionArgs() interface{} {
	return api.NewAppServiceActionArgs()
}

func newAppServiceActionResult() interface{} {
	return api.NewAppServiceActionResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Action(ctx context.Context, req *api.MgrReq) (r *api.Response, err error) {
	var _args api.AppServiceActionArgs
	_args.Req = req
	var _result api.AppServiceActionResult
	if err = p.c.Call(ctx, "Action", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
