// Code generated by Kitex v0.3.4. DO NOT EDIT.

package appservice

import (
	"github.com/cloudwego/kitex/server"
	"mgr-demo2/kitex_gen/thrift/kitex/api"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler api.AppService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
