// Code generated by Kitex v0.3.4. DO NOT EDIT.
package appservice

import (
	"github.com/cloudwego/kitex/server"
	"mgr-demo2/kitex_gen/thrift/kitex/api"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler api.AppService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
