kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
  apiServerAddress: 10.37.14.22
  apiServerPort: 6443
  podSubnet: "192.168.2.0/23"
  serviceSubnet: "192.168.230.0/24"
  kubeProxyMode: "ipvs"
nodes:
- role: control-plane
  image: kindest/node:v1.29.0
- role: worker
  image: kindest/node:v1.29.0
